load("@rules_rust//rust:defs.bzl", "rust_binary")

# Declares a Rust binary target with the given name.
rust_binary(
    name = "gate_layer_model",
    
    # Specifies the source file for the binary.
    srcs = ["src/main.rs"],
    
    # Specifies dependencies for the binary.
    deps = [
    ],
    edition = "2021"
)
